version: "3.7"
services:

  postgres-db:
    image: postgres:11.5-alpine
    container_name: template-postgres
    environment:
      - POSTGRES_USER=template
      - POSTGRES_PASSWORD=template
      - POSTGRES_DB=template-backend
    ports:
      - "5432:5432"
