---
swagger: "2.0"
info:
  title: Workplace Manager
  version: "0.0.1"
  description: Workpalace backend
basePath: "/api/v1"
produces: ["application/json"]

responses:

  BadRequest:
    description: Bad Request
    schema:
      $ref: "#/definitions/Problem"

  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Problem"

  Forbidden:
    description: Forbidden
    schema:
      $ref: "#/definitions/Problem"

  NotFound:
    description: Not Found
    schema:
      $ref: "#/definitions/Problem"

  Conflict:
    description: Conflict
    schema:
      $ref: "#/definitions/Problem"

  UnprocessableEntity:
    description: Unprocessable Entity
    schema:
      $ref: "#/definitions/Problem"

paths:
  # TODO: Remove this endpoint. Need to avoid NPE in swagger codegen task
  "/hello":
    get:
      operationId: helloWorld
      responses:
        "200":
          description: OK

definitions:

  Problem:
    type: object
    properties:
      type:
        type: string
        format: uri
      title:
        type: string
      status:
        type: integer
        format: int32
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
      detail:
        type: string
      instance:
        type: string
        format: uri
      violations:
        type: array
        items:
          $ref: "#/definitions/Violation"

  Violation:
    type: object
    properties:
      field:
        type: string
      message:
        type: string
